### ISSUE TITLE
window is not defined with nuxt.js

### ISSUE THREAD

**Issue by Silbad** [AmazingDreams/vue-matomo#79]
Hello,
I've an issue with nuxt.js 2.14.11 
```
 ERROR  window is not defined                                                                                                                                                                          14:14:18  

  at Object.<anonymous> (node_modules\vue-matomo\dist\vue-matomo.js:1:286)
  at Module._compile (internal/modules/cjs/loader.js:1015:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
  at Module.load (internal/modules/cjs/loader.js:879:32)
  at Function.Module._load (internal/modules/cjs/loader.js:724:14)
  at Module.require (internal/modules/cjs/loader.js:903:19)
  at require (internal/modules/cjs/helpers.js:74:18)
  at r (node_modules\vue-server-renderer\build.dev.js:9310:16)
  at Object.vue-matomo (webpack:/external "vue-matomo":1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../plugins/vue-matomo.js (plugins/vue-matomo.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../.nuxt/index.js (.nuxt/index.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module../.nuxt/server.js (.nuxt/server.js:1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
```
Thanks :)

**Comment by AmazingDreams** [comment]
Hello, have you loaded the plugin with SSR disabled? https://github.com/AmazingDreams/vue-matomo#nuxt

**Comment by Silbad** [comment]
My website is load with SSR, doesn't that cause any problems?

**Comment by AmazingDreams** [comment]
You can use vue-matomo with nuxt,  but you need to ensure it's not rendered server side as there is no browser context, as outlined in the example I linked above
